import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { readFile } from 'node:fs/promises';
import { uploadPrivateMedia } from '../src/admin/media-upload.ts';
import { AuthorizationError } from '../server/auth.ts';
import {
  createMediaAdminHandler,
  createMediaService,
  createSupabaseMediaDependencies,
  type MediaAsset,
  type MediaRepository,
  type MediaStorage,
} from '../server/media.ts';

const editor = '00000000-0000-0000-0000-000000000101';
const outsider = '00000000-0000-0000-0000-000000000102';

function validGlb(document: Record<string, unknown> = { asset: { version: '2.0' }, buffers: [], images: [] }, bin?: Uint8Array): Uint8Array {
  const json = new TextEncoder().encode(JSON.stringify(document));
  const padded = new Uint8Array(Math.ceil(json.length / 4) * 4);
  padded.set(json);
  padded.fill(0x20, json.length);
  const bytes = new Uint8Array(12 + 8 + padded.length + (bin ? 8 + Math.ceil(bin.length / 4) * 4 : 0));
  const view = new DataView(bytes.buffer);
  view.setUint32(0, 0x46546c67, true);
  view.setUint32(4, 2, true);
  view.setUint32(8, bytes.length, true);
  view.setUint32(12, padded.length, true);
  view.setUint32(16, 0x4e4f534a, true);
  bytes.set(padded, 20);
  if (bin) {
    const offset = 20 + padded.length;
    view.setUint32(offset, Math.ceil(bin.length / 4) * 4, true);
    view.setUint32(offset + 4, 0x004e4942, true);
    bytes.set(bin, offset + 8);
  }
  return bytes;
}

function validPng(): Uint8Array {
  return imageFixture('png');
}

// Genuine 2x2 RGB files encoded once with sharp; constants are not generated by the validator.
const imageFixtures = {
  png: 'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAEklEQVQImWP4ECDyIUCEAUIBACiuBVEdOquNAAAAAElFTkSuQmCC',
  jpeg: '/9j/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAACAAIDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEBAAAAAAAAAAAAAAAAAAAACP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AIkAVA/v/9k=',
  webp: 'UklGRjwAAABXRUJQVlA4IDAAAAAQAgCdASoCAAIAAUAmJaACdLoB+AH4AAPIAP7aJv/qcGDnz8oj/3jPOgub+tAAAAA=',
};

function imageFixture(format: keyof typeof imageFixtures): Uint8Array {
  return Uint8Array.from(globalThis.atob(imageFixtures[format]), (part) => part.charCodeAt(0));
}

function corruptImage(format: keyof typeof imageFixtures): Uint8Array {
  const bytes = imageFixture(format);
  if (format === 'jpeg') bytes[6] = 0xff; // Invalid quantization table, intact markers/lengths/frame/EOI.
  if (format === 'webp') bytes.fill(0xff, 30); // Intact RIFF/VP8 dimensions, broken compressed pixels.
  if (format === 'png') {
    const view = new DataView(bytes.buffer);
    for (let offset = 8; offset < bytes.length;) {
      const length = view.getUint32(offset);
      if (new TextDecoder().decode(bytes.slice(offset + 4, offset + 8)) === 'IDAT') {
        bytes.fill(0, offset + 8, offset + 8 + length);
        let crc = 0xffffffff;
        for (const byte of bytes.slice(offset + 4, offset + 8 + length)) {
          crc ^= byte;
          for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
        }
        view.setUint32(offset + 8 + length, (crc ^ 0xffffffff) >>> 0);
      }
      offset += length + 12;
    }
  }
  return bytes;
}

class MemoryRepository implements MediaRepository {
  readonly assets = new Map<string, MediaAsset>();
  readonly published = new Set<string>();
  readonly grants = new Map<string, { ownerId: string; bucket: string; key: string; expiresAt: string; finalized: boolean }>();
  failFinalize = false;
  clock = '2026-09-15T00:00:00.000Z';

  async createUploading(asset: MediaAsset): Promise<void> {
    this.assets.set(asset.id, asset);
  }

  async createUploadGrant(asset: MediaAsset): Promise<{ expiresAt: string }> {
    const expiresAt = new Date(Date.parse(this.clock) + 600_000).toISOString();
    this.grants.set(asset.id, { ownerId: asset.ownerId, bucket: asset.privateBucket, key: asset.privateKey, expiresAt, finalized: false });
    return { expiresAt };
  }

  async getAsset(id: string): Promise<MediaAsset | null> {
    return this.assets.get(id) ?? null;
  }

  async finalizeValidatedAsset(asset: MediaAsset, patch: { byteSize: number; mimeType: string; sha256: string }): Promise<MediaAsset | null> {
    if (this.failFinalize) throw new Error('RPC failed');
    const grant = this.grants.get(asset.id);
    if (!grant || grant.finalized || grant.ownerId !== asset.ownerId || grant.bucket !== asset.privateBucket || grant.key !== asset.privateKey || grant.expiresAt <= this.clock) return null;
    const ready: MediaAsset = { ...asset, ...patch, status: 'ready', finalizedAt: this.clock };
    grant.finalized = true;
    this.assets.set(asset.id, ready);
    return ready;
  }

  async setPublicKey(id: string, publicKey: string): Promise<void> {
    const asset = this.assets.get(id);
    if (!asset) throw new Error('missing asset');
    this.assets.set(id, { ...asset, publicKey });
  }

  async findPublishedReadyAsset(id: string): Promise<MediaAsset | null> {
    const asset = this.assets.get(id);
    return asset && asset.status === 'ready' && asset.publicKey && this.published.has(id) ? asset : null;
  }
}

class MemoryStorage implements MediaStorage {
  readonly objects = new Map<string, Uint8Array>();
  readonly copied: Array<{ sourceKey: string; destinationKey: string }> = [];
  failCopy = false;
  failRead = false;

  async getObject(bucket: string, key: string): Promise<Uint8Array | null> {
    if (this.failRead) throw new Error('Storage read failed');
    return this.objects.get(bucket + '/' + key) ?? null;
  }

  async createSignedUrl(bucket: string, key: string, expiresInSeconds: number): Promise<string> {
    return 'https://preview.example.test/' + bucket + '/' + key + '?ttl=' + expiresInSeconds;
  }

  async copyObject(
    sourceBucket: string,
    sourceKey: string,
    destinationBucket: string,
    destinationKey: string,
  ): Promise<void> {
    if (this.failCopy) throw new Error('copy failed');
    const bytes = this.objects.get(sourceBucket + '/' + sourceKey);
    if (!bytes) throw new Error('missing source');
    this.objects.set(destinationBucket + '/' + destinationKey, bytes);
    this.copied.push({ sourceKey, destinationKey });
  }

  publicUrl(bucket: string, key: string): string {
    return 'https://public.example.test/' + bucket + '/' + key;
  }
}

function fixture() {
  const repository = new MemoryRepository();
  const storage = new MemoryStorage();
  let number = 1;
  const service = createMediaService({
    repository,
    storage,
    newId: () => '00000000-0000-4000-8000-' + String(number++).padStart(12, '0'),
    now: () => new Date('2026-09-15T00:00:00.000Z'),
  });
  return { repository, storage, service };
}

function request(path: string, method = 'GET', token?: string, body?: unknown): Request {
  return new Request('https://cms.example.test' + path, {
    method,
    headers: {
      ...(token ? { authorization: 'Bearer ' + token } : {}),
      ...(body === undefined ? {} : { 'content-type': 'application/json' }),
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
}

describe('media lifecycle', () => {
  it('returns a user-bound exact private path and a ten-minute expiry without a signed upload token', async () => {
    const { service, repository } = fixture();
    const result = await service.authorizeUpload(editor, { type: 'image', bytes: 1024 });
    assert.equal(result.status, 201);
    if (result.status !== 201) return;
    assert.equal(result.data.expiresAt, '2026-09-15T00:10:00.000Z');
    assert.equal('uploadToken' in result.data, false);
    assert.equal('uploadUrl' in result.data, false);
    assert.equal(repository.grants.get(result.data.asset.id)?.ownerId, editor);
    assert.equal(repository.grants.get(result.data.asset.id)?.key, result.data.privateKey);
  });

  for (const format of ['png', 'jpeg', 'webp'] as const) {
    it('fully decodes a genuine ' + format + ' before marking it ready', async () => {
      const { service, storage } = fixture();
      const bytes = imageFixture(format);
      const upload = await service.authorizeUpload(editor, { type: 'image', bytes: bytes.length });
      assert.equal(upload.status, 201);
      if (upload.status !== 201) return;
      storage.objects.set('cms-media-private/' + upload.data.privateKey, bytes);
      const result = await service.finalizeUpload(editor, upload.data.asset.id);
      assert.equal(result.status, 200);
      if (result.status === 200) assert.equal(result.data.mimeType, 'image/' + format);
    });

    it('rejects header-valid corrupt ' + format + ' without consuming the grant', async () => {
      const { service, storage, repository } = fixture();
      const bytes = corruptImage(format);
      const upload = await service.authorizeUpload(editor, { type: 'image', bytes: bytes.length });
      assert.equal(upload.status, 201);
      if (upload.status !== 201) return;
      storage.objects.set('cms-media-private/' + upload.data.privateKey, bytes);
      assert.equal((await service.finalizeUpload(editor, upload.data.asset.id)).status, 400);
      assert.equal((await repository.getAsset(upload.data.asset.id))?.status, 'uploading');
      storage.objects.set('cms-media-private/' + upload.data.privateKey, imageFixture(format));
      assert.equal((await service.finalizeUpload(editor, upload.data.asset.id)).status, 200);
    });
  }

  for (const failure of ['missing', 'read', 'rpc'] as const) {
    it('can retry finalization after a ' + failure + ' failure', async () => {
      const { service, storage, repository } = fixture();
      const upload = await service.authorizeUpload(editor, { type: 'image', bytes: validPng().length });
      assert.equal(upload.status, 201);
      if (upload.status !== 201) return;
      if (failure !== 'missing') storage.objects.set('cms-media-private/' + upload.data.privateKey, validPng());
      storage.failRead = failure === 'read';
      repository.failFinalize = failure === 'rpc';
      assert.equal((await service.finalizeUpload(editor, upload.data.asset.id)).status, failure === 'missing' ? 400 : 502);
      assert.equal((await repository.getAsset(upload.data.asset.id))?.status, 'uploading');
      storage.failRead = false;
      repository.failFinalize = false;
      storage.objects.set('cms-media-private/' + upload.data.privateKey, validPng());
      assert.equal((await service.finalizeUpload(editor, upload.data.asset.id)).status, 200);
    });
  }

  it('rejects another verified user and rechecks expiry at the finalization transaction', async () => {
    const { service, storage, repository } = fixture();
    const upload = await service.authorizeUpload(editor, { type: 'image', bytes: validPng().length });
    assert.equal(upload.status, 201);
    if (upload.status !== 201) return;
    storage.objects.set('cms-media-private/' + upload.data.privateKey, validPng());
    assert.equal((await service.finalizeUpload(outsider, upload.data.asset.id)).status, 404);
    repository.clock = '2026-09-15T00:10:00.000Z';
    assert.equal((await service.finalizeUpload(editor, upload.data.asset.id)).status, 409);
    assert.equal((await repository.getAsset(upload.data.asset.id))?.status, 'uploading');
  });

  it('accepts the existing repository GLB fixture', async () => {
    const { service, storage } = fixture();
    const bytes = new Uint8Array(await readFile(new URL('../public/assets/courtyard_building_webgl.glb', import.meta.url)));
    const upload = await service.authorizeUpload(editor, { type: 'glb', bytes: bytes.length });
    assert.equal(upload.status, 201);
    if (upload.status !== 201) return;
    storage.objects.set('cms-media-private/' + upload.data.privateKey, bytes);
    assert.equal((await service.finalizeUpload(editor, upload.data.asset.id)).status, 200);
  });

  const imageUri = 'data:image/png;base64,' + imageFixtures.png;
  const glbCases: Array<{ name: string; document: Record<string, unknown>; bin?: Uint8Array; status: number }> = [
    { name: 'valid BIN bufferView image', document: { buffers: [{ byteLength: validPng().length }], bufferViews: [{ buffer: 0, byteOffset: 0, byteLength: validPng().length }], images: [{ bufferView: 0, mimeType: 'image/png' }] }, bin: validPng(), status: 200 },
    { name: 'valid data URI image', document: { images: [{ uri: imageUri }] }, status: 200 },
    { name: 'valid data buffer image', document: { buffers: [{ uri: imageUri, byteLength: validPng().length }], bufferViews: [{ buffer: 0, byteLength: validPng().length }], images: [{ bufferView: 0, mimeType: 'image/png' }] }, status: 200 },
    { name: 'short decoded data buffer', document: { buffers: [{ uri: 'data:application/octet-stream;base64,AAAA', byteLength: 100 }] }, status: 400 },
    { name: 'negative view offset', document: { buffers: [{ byteLength: 4 }], bufferViews: [{ buffer: 0, byteOffset: -1, byteLength: 1 }] }, bin: new Uint8Array(4), status: 400 },
    { name: 'string view index', document: { buffers: [{ byteLength: 4 }], bufferViews: [{ buffer: '0', byteLength: 1 }] }, bin: new Uint8Array(4), status: 400 },
    { name: 'fractional view length', document: { buffers: [{ byteLength: 4 }], bufferViews: [{ buffer: 0, byteLength: 1.5 }] }, bin: new Uint8Array(4), status: 400 },
    { name: 'view beyond actual data', document: { buffers: [{ uri: 'data:application/octet-stream;base64,AAAA', byteLength: 3 }], bufferViews: [{ buffer: 0, byteLength: 4 }] }, status: 400 },
    { name: 'unresolved buffer', document: { bufferViews: [{ buffer: 0, byteLength: 4 }] }, status: 400 },
    { name: 'unresolved image view', document: { images: [{ bufferView: 0, mimeType: 'image/png' }] }, status: 400 },
    { name: 'missing image source', document: { images: [{ mimeType: 'image/png' }] }, status: 400 },
    { name: 'wrong embedded MIME', document: { images: [{ uri: imageUri, mimeType: 'image/jpeg' }] }, status: 400 },
    { name: 'wrong bufferView MIME', document: { buffers: [{ byteLength: validPng().length }], bufferViews: [{ buffer: 0, byteLength: validPng().length }], images: [{ bufferView: 0, mimeType: 'image/jpeg' }] }, bin: validPng(), status: 400 },
    { name: 'external image', document: { images: [{ uri: 'https://example.test/a.png' }] }, status: 400 },
    { name: 'corrupt bufferView image', document: { buffers: [{ byteLength: validPng().length }], bufferViews: [{ buffer: 0, byteLength: validPng().length }], images: [{ bufferView: 0, mimeType: 'image/png' }] }, bin: corruptImage('png'), status: 400 },
  ];
  for (const example of glbCases) {
    it('validates GLB: ' + example.name, async () => {
      const { service, storage } = fixture();
      const bytes = validGlb({ asset: { version: '2.0' }, ...example.document }, example.bin);
      const upload = await service.authorizeUpload(editor, { type: 'glb', bytes: bytes.length });
      assert.equal(upload.status, 201);
      if (upload.status !== 201) return;
      storage.objects.set('cms-media-private/' + upload.data.privateKey, bytes);
      assert.equal((await service.finalizeUpload(editor, upload.data.asset.id)).status, example.status);
    });
  }

  it('sends direct Storage uploads with the signed user JWT, never a service or upload token', async () => {
    let captured: { url: string; init?: RequestInit } | undefined;
    await uploadPrivateMedia({
      supabaseUrl: 'https://project.supabase.co', publishableKey: 'public-key', accessToken: 'signed-user-jwt',
      grant: { privateBucket: 'cms-media-private', privateKey: 'private/00000000-0000-4000-8000-000000000001', expiresAt: '2099-01-01T00:00:00.000Z' },
      file: new Blob([new Uint8Array(validPng()).buffer]), mimeType: 'image/png',
      fetcher: async (url, init) => { captured = { url: String(url), init }; return new Response('{}'); },
    });
    assert.equal(captured?.url, 'https://project.supabase.co/storage/v1/object/cms-media-private/private/00000000-0000-4000-8000-000000000001');
    assert.equal(new Headers(captured?.init?.headers).get('authorization'), 'Bearer signed-user-jwt');
    assert.equal(new Headers(captured?.init?.headers).get('x-upsert'), 'false');
  });

  it('persists non-null pending base fields and finalizes only through the validated service RPC', async () => {
    const calls: Array<{ url: string; body: Record<string, unknown> }> = [];
    const { repository } = createSupabaseMediaDependencies(async (url, init) => {
      calls.push({ url: String(url), body: JSON.parse(String(init?.body)) });
      return new Response('[]', { headers: { 'content-type': 'application/json' } });
    }, 'https://project.supabase.co', 'server-only-key');
    const { service } = fixture();
    const upload = await service.authorizeUpload(editor, { type: 'image', bytes: 10 });
    if (upload.status !== 201) throw new Error('Expected authorization');
    await repository.createUploading(upload.data.asset);
    assert.equal(calls[0].body.mime_type, 'application/octet-stream');
    assert.equal(calls[0].body.byte_size, 0);
    await repository.finalizeValidatedAsset(upload.data.asset, { byteSize: 10, mimeType: 'image/png', sha256: 'a'.repeat(64) });
    assert.equal(calls[1].url, 'https://project.supabase.co/rest/v1/rpc/finalize_media_upload');
    assert.equal(calls[1].body.verified_user_id, editor);
    assert.equal(calls[1].body.expected_path, upload.data.privateKey);
  });

  it('rejects oversized authorization requests before creating a grant', async () => {
    const { service } = fixture();
    const result = await service.authorizeUpload(editor, { type: 'glb', bytes: 26 * 1024 * 1024 });

    assert.equal(result.status, 400);
  });

  it('rejects renamed non-GLB bytes during finalization', async () => {
    const { service, storage } = fixture();
    const upload = await service.authorizeUpload(editor, { type: 'glb', bytes: 16 });
    assert.equal(upload.status, 201);
    if (upload.status !== 201) return;
    storage.objects.set('cms-media-private/' + upload.data.privateKey, new TextEncoder().encode('script'));

    const result = await service.finalizeUpload(editor, upload.data.asset.id);
    assert.equal(result.status, 400);
  });

  it('does not issue grants or permit admin routes without media.manage', async () => {
    const { service } = fixture();
    const handler = createMediaAdminHandler({
      service,
      requireCapability: async () => {
        throw new AuthorizationError(403, 'FORBIDDEN', 'You do not have this capability.');
      },
    });

    const response = await handler(request('/api/admin/media/upload', 'POST', 'no-media-grant', {
      type: 'image',
      bytes: 1024,
    }));
    assert.equal(response.status, 403);
    const body = (await response.json()) as { error: { requestId: string } };
    assert.equal(response.headers.get('x-request-id'), body.error.requestId);
  });

  it('returns a private, ten-minute signed preview URL only to media managers', async () => {
    const { service, storage } = fixture();
    const upload = await service.authorizeUpload(editor, { type: 'image', bytes: validPng().length });
    assert.equal(upload.status, 201);
    if (upload.status !== 201) return;
    storage.objects.set('cms-media-private/' + upload.data.privateKey, validPng());
    assert.equal((await service.finalizeUpload(editor, upload.data.asset.id)).status, 200);

    const handler = createMediaAdminHandler({
      service,
      requireCapability: async (incoming) => {
        if (incoming.headers.get('authorization') !== 'Bearer media-manager') {
          throw new AuthorizationError(403, 'FORBIDDEN', 'You do not have this capability.');
        }
        return { userId: editor };
      },
    });
    const denied = await handler(request('/api/admin/media/' + upload.data.asset.id + '/preview', 'GET', 'bad'));
    const allowed = await handler(
      request('/api/admin/media/' + upload.data.asset.id + '/preview', 'GET', 'media-manager'),
    );

    assert.equal(denied.status, 403);
    assert.equal(allowed.status, 200);
    assert.match((await allowed.json() as { data: { url: string } }).data.url, /^https:\/\/preview/);
    assert.match(allowed.headers.get('cache-control') ?? '', /private/);
  });

  it('leaves an asset without a public key when copy to immutable storage fails', async () => {
    const { service, storage, repository } = fixture();
    const upload = await service.authorizeUpload(editor, { type: 'glb', bytes: validGlb().length });
    assert.equal(upload.status, 201);
    if (upload.status !== 201) return;
    storage.objects.set('cms-media-private/' + upload.data.privateKey, validGlb());
    assert.equal((await service.finalizeUpload(editor, upload.data.asset.id)).status, 200);
    storage.failCopy = true;

    const result = await service.copyReadyAssetToPublic(upload.data.asset.id);
    assert.equal(result.status, 502);
    assert.equal((await repository.getAsset(upload.data.asset.id))?.publicKey, null);
  });

  it('resolves only immutable, ready assets referenced by an active published revision', async () => {
    const { service, storage, repository } = fixture();
    const upload = await service.authorizeUpload(editor, { type: 'image', bytes: validPng().length });
    assert.equal(upload.status, 201);
    if (upload.status !== 201) return;
    storage.objects.set('cms-media-private/' + upload.data.privateKey, validPng());
    assert.equal((await service.finalizeUpload(editor, upload.data.asset.id)).status, 200);

    assert.equal((await service.copyReadyAssetToPublic(upload.data.asset.id)).status, 200);
    assert.equal((await service.resolvePublishedMedia(upload.data.asset.id)).status, 404);
    repository.published.add(upload.data.asset.id);

    const resolved = await service.resolvePublishedMedia(upload.data.asset.id);
    assert.equal(resolved.status, 200);
    if (resolved.status === 200) {
      assert.match(resolved.data.key, /^assets\/[0-9a-f-]{36}\/[a-f0-9]{64}$/);
      assert.match(resolved.data.url, /^https:\/\/public/);
    }
  });

  it('does not expose private storage paths through public resolution', async () => {
    const { service, storage, repository } = fixture();
    const upload = await service.authorizeUpload(outsider, { type: 'image', bytes: validPng().length });
    assert.equal(upload.status, 201);
    if (upload.status !== 201) return;
    storage.objects.set('cms-media-private/' + upload.data.privateKey, validPng());
    assert.equal((await service.finalizeUpload(outsider, upload.data.asset.id)).status, 200);
    repository.published.add(upload.data.asset.id);

    const result = await service.resolvePublishedMedia(upload.data.asset.id);
    assert.equal(result.status, 404);
  });
});
